### ISSUE TITLE
Support for "copy" and "test" operations

### ISSUE THREAD

**Issue by mestag-a** [flipkart-incubator/zjsonpatch#12] opened 2016-03-18 14:06 UTC
Hi. I was wondering why there seemed to be no support for "copy" and "test" operations (both specified by the RFC).
Is it currently in development ? If not, is it planned ?

**Comment by vishwakarma** [comment] 2016-05-01 09:23
Hey, extremely sorry for such a late response.
The "copy" & "test" operations are currently not supported, i will be incorporating them soon. Meanwhile i  will happy, if you are interested in making a PR for same.
Thanks

**Comment by acsadam0404** [comment] 2017-03-20 18:56
Will this ever be implemented? I looked at the other json patch implementation only because of missing copy operation, but yours are 5x faster! It would be nice if you could implement it :)

**Comment by vishwakarma** [comment] 2017-03-20 19:13
Sure, I will try best to incorporate copy & test operations by end of this week.

**Comment by vishwakarma** [comment] 2017-03-22 07:49
Hi @acsadam0404, i have made the changes in "copy-test-op" branch, currently i m testing & refactoring it, let me know if u wana give it a try too.

**Comment by acsadam0404** [comment] 2017-03-22 18:10
@vishwakarma i'm not available today and tomorrow but in friday i would definitely want to give it a try! Thanks for this!

**Comment by vishwakarma** [comment] 2017-03-23 07:27
Hi @acsadam0404 , i have currently tested it against existing 128 test cases and 1000 programmatically generated test cases, looks good.
Please let me know any test case  or any unexpected behaviour which u come across while testing.

**Comment by vishwakarma** [comment] 2017-03-27 07:59
Hi @acsadam0404 
Let me know if got  chance to test this, if all ok, then shall merge it with master and release it ?

**Comment by acsadam0404** [comment] 2017-03-27 09:34
@vishwakarma I tested it and it seems all right for me. I really appreciate your work. 

In my app (which is not yet in production) I use this extensively, with ~5 patch/sec data so if there is any error arise we will know it soon.

**Comment by vishwakarma** [comment] 2017-03-27 12:24
cool
Thanks, i will release it today then.
i will update you here once released.

**Comment by vishwakarma** [comment] 2017-03-27 12:36
I have released 0.3.1, please go ahead and try it.
thanks again for testing

**Closed by vishwakarma** 2017-03-27 12:36 UTC
