### ISSUE TITLE
Normalize to move & copy sometimes produces broken patches

### ISSUE THREAD

**Issue by mahe-work** [flipkart-incubator/zjsonpatch#72] opened 2018-04-18 12:22 UTC
We have been keeping a version history of documents stored into MongoDB by storing every single version of the whole documents into a separate journal collection. This journal is starting to grow uncontrollably and since mongodb stores json documents, we're investigating changing the journal format to jsonpatches to reduce the size of the collection.

We have evaluated zjsonpatch library and found that in a vast majority of cases it works flawlessly: We can calculate patches between hundreds of document versions and apply them in original order to produce a document that is identical with the one we have in mongodb. 

In fact, if we use DiffFlags.dontNormalizeOpIntoMoveAndCopy() there are no problems whatsoever! The only caveat with this is that the size of the colleciton is 1,5 times larger with this approach but it is a fact we can live with.

However, in a very small minority (we're talking fractions of a percent) of cases, without  DiffFlags.dontNormalizeOpIntoMoveAndCopy()  a sufficiently large change in document between versions produces a patch that cannot be applied. We've got several different error messages in these cases, such as jsonPatch.noSuchPath,  parent is not a container etc.

Common to all these cases is that changes in document both reorder some nested object arrays and also at the same time remove fields inside those reordered array items. 

Typically this is the case when we remove a field in a domain object class whose instances are stored as an unordered collection such as a set inside other domain objects. Removing the field from all instances and saving the document changes nested object identities and collection's order gets shuffled which produces a very large jsonpatch.

I've been trying to produce a simplified failing test case for your inspection but no luck so far. I'll let you know if I can reproduce the problem with sufficiently small data.

**Comment by vishwakarma** [comment] 2018-04-18 12:47
Hi @mahe-kl, Thanks for writing in
I am glad that this project is useful to you. 
Meanwhile, if you could send even the large test cases which are failing, I would debug them.

**Comment by mahe-kl** [comment] 2018-04-25 06:36
The problem is, this happens with production customer data which I cannot share with you. I have to try to come up with an artificial test case for your inspection.

**Comment by vishwakarma** [comment] 2018-04-25 06:41
If possible, can you mask the production data and share?
Like if the data contains user's name then you may mask it with other string and same for other fields?

**Comment by mahe-kl** [comment] 2018-04-25 06:43
I will definitely try as soon as I have little time to dedicate for this issue.

**Comment by holograph** [comment] 2018-06-11 06:47
Alternatively, can you re-run the test with just `DiffFlags.OMIT_MOVE_OPERATION`, and subsequently with `DiffFlags.OMIT_COPY_OPERATION`? Will help narrow the problem down.

**Comment by holograph** [comment] 2018-06-11 06:52
This is likely in the `MOVE` generation path:

```
                Diff moveDiff = null;
                if (Operation.REMOVE == diff1.getOperation() &&
                        Operation.ADD == diff2.getOperation()) {
                    computeRelativePath(diff2.getPath(), i + 1, j - 1, diffs);
                    moveDiff = new Diff(Operation.MOVE, diff1.getPath(), diff2.getPath());

                } else if (Operation.ADD == diff1.getOperation() &&
                        Operation.REMOVE == diff2.getOperation()) {
                    computeRelativePath(diff2.getPath(), i, j - 1, diffs); // diff1's add should also be considered
                    moveDiff = new Diff(Operation.MOVE, diff2.getPath(), diff1.getPath());
                }
                if (moveDiff != null) {
                    diffs.remove(j);
                    diffs.set(i, moveDiff);
                    break;
                }
```

This can actually subtly change the ordering in the resulting diff sequence. I'll try to construct a valid example but my connectivity is pretty bad where I am, so it might take a while.

**Comment by holograph** [comment] 2019-02-13 20:57
Well no dice on constructing a bespoke example. If anyone has a repro case I'd be happy to look this over, please do comment here (or on a new issue). In the meantime I'm closing this...

**Closed by holograph** 2019-02-13 20:57 UTC
